version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.30.1-rootless
    ports:
      - '8181:8181'
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--log-level=debug"
      - "--set=services.opa-bundle-generator.url=http://host.docker.internal:8082/v1/opa-bundle-generator/"
      - "--set=bundles.permission-bundle.service=opa-bundle-generator"
      - "--set=bundles.permission-bundle.resource=bundles/bundle.tar.gz"
      - "--set=bundles.permission-bundle.polling.min_delay_seconds=60"
      - "--set=bundles.permission-bundle.polling.max_delay_seconds=120"